# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  SympleLang_config = debug

else ifeq ($(config),release)
  SympleLang_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := SympleLang

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

SympleLang:
ifneq (,$(SympleLang_config))
	@echo "==== Building SympleLang ($(SympleLang_config)) ===="
	@${MAKE} --no-print-directory -C SympleLang -f Makefile config=$(SympleLang_config)
endif

clean:
	@${MAKE} --no-print-directory -C SympleLang -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   SympleLang"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"